version: ${VERSION}
services:
  db:
    image: postgres
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes: 
      - GDDKiA_data:/var/lib/postgresql/data
volumes:
  GDDKiA_data: