--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 10.0.1004
--   Created On : wtorek, 01 listopad, 2022 
--   DBMS       : PostgreSQL 
--   -------------------------------------------------- 


--  Drop Tables, Stored Procedures and Views

DROP TABLE road_node CASCADE
;
DROP TABLE road CASCADE
;
DROP TABLE car_data CASCADE
;
DROP TABLE car CASCADE
;
DROP TABLE app_user CASCADE
;
DROP TYPE user_role CASCADE
;
DROP TYPE car_type CASCADE
;

CREATE TYPE user_role AS ENUM ('USER', 'POLICE_OFFICER', 'ADMIN','EMPLOYEE','CAR_OWNER')
;

CREATE TYPE car_type AS ENUM ('MINIVAN', 'PICKUP_TRUCK', 'SEDAN','HATCHBACK')
;

--  Create Tables 
CREATE TABLE road_node
(
    id      integer        NOT NULL,
    road_id integer        NOT NULL,
    x       decimal(10, 2) NOT NULL,
    y       decimal(10, 2) NOT NULL
)
;

CREATE TABLE road
(
    id                 integer        NOT NULL,
    start_road_node_id integer        NOT NULL,
    end_road_node_id   integer        NOT NULL,
    length             decimal(10, 2) NOT NULL,
    name               varchar(100)   NOT NULL
)
;

CREATE TABLE car_data
(
    id              integer NOT NULL,
    car_id          integer NOT NULL,
    engine_capacity decimal(10, 2),
    height          decimal(10, 2),
    length          decimal(10, 2),
    model           varchar(50),
    production_year integer,
    type            car_type ,
    weight          decimal(10, 2),
    width           decimal(10, 2),
    make            varchar(50)
)
;

CREATE TABLE car
(
    id                  integer NOT NULL,
    user_id             integer NOT NULL,
    registration_number char(8) NOT NULL
)
;

CREATE TABLE app_user
(
    id           integer     NOT NULL,
    user_role    user_role   NOT NULL,
    email        varchar(50) NOT NULL,
    first_name   varchar(50) NOT NULL,
    last_name    varchar(50) NOT NULL,
    phone_number varchar(11) NOT NULL
)
;


--  Create Indexes 
ALTER TABLE car_data
    ADD CONSTRAINT UQ_car_data_car_id UNIQUE (car_id)
;
ALTER TABLE car
    ADD CONSTRAINT UQ_car_registration_number UNIQUE (registration_number)
;
ALTER TABLE app_user
    ADD CONSTRAINT UQ_user_phone_number UNIQUE (phone_number)
;
ALTER TABLE app_user
    ADD CONSTRAINT UQ_user_email UNIQUE (email)
;
--  Create Primary Key Constraints 
ALTER TABLE road_node
    ADD CONSTRAINT PK_road_node
        PRIMARY KEY (id)
;


ALTER TABLE road
    ADD CONSTRAINT PK_road
        PRIMARY KEY (id)
;

ALTER TABLE car_data
    ADD CONSTRAINT PK_car_data
        PRIMARY KEY (id)
;


ALTER TABLE car
    ADD CONSTRAINT PK_car
        PRIMARY KEY (id)
;


ALTER TABLE app_user
    ADD CONSTRAINT PK_user
        PRIMARY KEY (id)
;


--  Create Foreign Key Constraints
ALTER TABLE car_data
    ADD CONSTRAINT FK_car_data_car
        FOREIGN KEY (car_id) REFERENCES car (id)
;

ALTER TABLE car
    ADD CONSTRAINT FK_car_user
        FOREIGN KEY (user_id) REFERENCES app_user (id)
;